//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnBoard.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        internal static string AboutBox {
            get {
                return ResourceManager.GetString("AboutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Tutma İptal Talebi Kabul Edildi.....
        /// </summary>
        internal static string CancelHoldStationAccepted {
            get {
                return ResourceManager.GetString("CancelHoldStationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Atlama İptali Talebi Kabul Edildi.....
        /// </summary>
        internal static string CancelSkipStationAcceptMessage {
            get {
                return ResourceManager.GetString("CancelSkipStationAcceptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Atlama İptal Talebi Reddedildi.....
        /// </summary>
        internal static string CancelSkipStationRejectMessage {
            get {
                return ResourceManager.GetString("CancelSkipStationRejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar Dosyası Bulanamadı!.
        /// </summary>
        internal static string CheckSerilizationFileExceptionMessage {
            get {
                return ResourceManager.GetString("CheckSerilizationFileExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapılar Kapandı....
        /// </summary>
        internal static string CloseDoors {
            get {
                return ResourceManager.GetString("CloseDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnBoard yeni ayarlarla çalışmaya başlayacak..
        /// </summary>
        internal static string CloseSettingsMessage {
            get {
                return ResourceManager.GetString("CloseSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı Ayarları.
        /// </summary>
        internal static string CommunicationSettingsModal {
            get {
                return ResourceManager.GetString("CommunicationSettingsModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlandı... - .
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı Hatası... - .
        /// </summary>
        internal static string ConnectionFailure {
            get {
                return ResourceManager.GetString("ConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar Okunamadı!.
        /// </summary>
        internal static string DeSerilizationSettingsExceptionMessage {
            get {
                return ResourceManager.GetString("DeSerilizationSettingsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Hat Bloğu ID.
        /// </summary>
        internal static string Front_Track_ID {
            get {
                return ResourceManager.GetString("Front_Track_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Hat Bloğu Boyu(cm).
        /// </summary>
        internal static string Front_Track_Length {
            get {
                return ResourceManager.GetString("Front_Track_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ön Hat Bloğu Konumu(cm).
        /// </summary>
        internal static string Front_Track_Location {
            get {
                return ResourceManager.GetString("Front_Track_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Track Max Speed(km/sa).
        /// </summary>
        internal static string Front_Track_Max_Speed {
            get {
                return ResourceManager.GetString("Front_Track_Max_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string GeneralSettingsModal {
            get {
                return ResourceManager.GetString("GeneralSettingsModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Tutma Talebi Kabul Edildi.....
        /// </summary>
        internal static string HoldStationAcceptMessage {
            get {
                return ResourceManager.GetString("HoldStationAcceptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Tutma Talebi Reddedildi....
        /// </summary>
        internal static string HoldStationRejectMessage {
            get {
                return ResourceManager.GetString("HoldStationRejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Adresi : .
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayakizi Hat Bloğu.
        /// </summary>
        internal static string ListviewColumnFoot {
            get {
                return ResourceManager.GetString("ListviewColumnFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat Blokları.
        /// </summary>
        internal static string ListviewColumnRouteTrack {
            get {
                return ResourceManager.GetString("ListviewColumnRouteTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hız Sınırı(km/sa).
        /// </summary>
        internal static string ListviewColumnSpeed {
            get {
                return ResourceManager.GetString("ListviewColumnSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon.
        /// </summary>
        internal static string ListviewColumnStation {
            get {
                return ResourceManager.GetString("ListviewColumnStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snl. Meş. Hat Blo..
        /// </summary>
        internal static string ListviewColumnVir {
            get {
                return ResourceManager.GetString("ListviewColumnVir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loglar Yazılamıyor!.
        /// </summary>
        internal static string LoggingExceptionMessage {
            get {
                return ResourceManager.GetString("LoggingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygula.
        /// </summary>
        internal static string m_buttonApply {
            get {
                return ResourceManager.GetString("m_buttonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string m_buttonSave {
            get {
                return ResourceManager.GetString("m_buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logları SQL&apos; e Kaydet.
        /// </summary>
        internal static string m_checkBoxSQLLogs {
            get {
                return ResourceManager.GetString("m_checkBoxSQLLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı.
        /// </summary>
        internal static string m_communicationItem {
            get {
                return ResourceManager.GetString("m_communicationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel.
        /// </summary>
        internal static string m_generalItem {
            get {
                return ResourceManager.GetString("m_generalItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenler.
        /// </summary>
        internal static string m_groupBoxAllTrains {
            get {
                return ResourceManager.GetString("m_groupBoxAllTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loglar.
        /// </summary>
        internal static string m_groupBoxLog {
            get {
                return ResourceManager.GetString("m_groupBoxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren Parametreleri.
        /// </summary>
        internal static string m_groupBoxTrainSettings {
            get {
                return ResourceManager.GetString("m_groupBoxTrainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Tren Ayarları.
        /// </summary>
        internal static string m_groupBoxTrainSettingsModal {
            get {
                return ResourceManager.GetString("m_groupBoxTrainSettingsModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren Başlatma Sıklığı.
        /// </summary>
        internal static string m_groupBoxTrainStart {
            get {
                return ResourceManager.GetString("m_groupBoxTrainStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Sıklığı.
        /// </summary>
        internal static string m_groupBoxWorkingCycle {
            get {
                return ResourceManager.GetString("m_groupBoxWorkingCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlanma İvmesi :.
        /// </summary>
        internal static string m_labelCurrentAcceleration {
            get {
                return ResourceManager.GetString("m_labelCurrentAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum (cm) :.
        /// </summary>
        internal static string m_labelCurrentLocation {
            get {
                return ResourceManager.GetString("m_labelCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hız(km/sa) :.
        /// </summary>
        internal static string m_labelCurrentTrainSpeedKM {
            get {
                return ResourceManager.GetString("m_labelCurrentTrainSpeedKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapı Durumu :.
        /// </summary>
        internal static string m_labelDoorStatus {
            get {
                return ResourceManager.GetString("m_labelDoorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door Timer Counter :.
        /// </summary>
        internal static string m_labelDoorTimerCounter {
            get {
                return ResourceManager.GetString("m_labelDoorTimerCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Hızlanma İvmesi(m/s²) :.
        /// </summary>
        internal static string m_labelMaxTrainAcceleration {
            get {
                return ResourceManager.GetString("m_labelMaxTrainAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Yavaşlama İvmesi (m/s²) :.
        /// </summary>
        internal static string m_labelMaxTrainDeceleration {
            get {
                return ResourceManager.GetString("m_labelMaxTrainDeceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dakika :.
        /// </summary>
        internal static string m_labelMinute {
            get {
                return ResourceManager.GetString("m_labelMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon Zamanı (ms) :.
        /// </summary>
        internal static string m_labelOperationTime {
            get {
                return ResourceManager.GetString("m_labelOperationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Hat Bloğu Konumu (cm) :.
        /// </summary>
        internal static string m_labelRearCurrentLocation {
            get {
                return ResourceManager.GetString("m_labelRearCurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saniye :.
        /// </summary>
        internal static string m_labelSecond {
            get {
                return ResourceManager.GetString("m_labelSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicil No : .
        /// </summary>
        internal static string m_labelStaffID {
            get {
                return ResourceManager.GetString("m_labelStaffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren Uzunluğu (cm) :.
        /// </summary>
        internal static string m_labelTrainLengthCM {
            get {
                return ResourceManager.GetString("m_labelTrainLengthCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenler : .
        /// </summary>
        internal static string m_labelTrains {
            get {
                return ResourceManager.GetString("m_labelTrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren Hız Limiti (km/h) :.
        /// </summary>
        internal static string m_labelTrainSpeedLimit {
            get {
                return ResourceManager.GetString("m_labelTrainSpeedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Gönder (ms) :.
        /// </summary>
        internal static string m_labelWorkingCycleMessageSend {
            get {
                return ResourceManager.GetString("m_labelWorkingCycleMessageSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBATC (ms) :.
        /// </summary>
        internal static string m_labelWorkingCycleOBATC {
            get {
                return ResourceManager.GetString("m_labelWorkingCycleOBATC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Yenileme (ms) :.
        /// </summary>
        internal static string m_labelWorkingUIRefresh {
            get {
                return ResourceManager.GetString("m_labelWorkingUIRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string m_settingsPopup {
            get {
                return ResourceManager.GetString("m_settingsPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı.
        /// </summary>
        internal static string m_tabPageCommunication {
            get {
                return ResourceManager.GetString("m_tabPageCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Mesaj.
        /// </summary>
        internal static string m_tabPageIncomingMessage {
            get {
                return ResourceManager.GetString("m_tabPageIncomingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loglar.
        /// </summary>
        internal static string m_tabPageLogsGeneralSettings {
            get {
                return ResourceManager.GetString("m_tabPageLogsGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giden Mesaj.
        /// </summary>
        internal static string m_tabPageOutgoingMessage {
            get {
                return ResourceManager.GetString("m_tabPageOutgoingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        internal static string m_tabPageRoute {
            get {
                return ResourceManager.GetString("m_tabPageRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren.
        /// </summary>
        internal static string m_tabPageTrain {
            get {
                return ResourceManager.GetString("m_tabPageTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren Başlat.
        /// </summary>
        internal static string m_tabPageTrainGeneralSettings {
            get {
                return ResourceManager.GetString("m_tabPageTrainGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren.
        /// </summary>
        internal static string m_trainItem {
            get {
                return ResourceManager.GetString("m_trainItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapılar Açıldı....
        /// </summary>
        internal static string OpenDoors {
            get {
                return ResourceManager.GetString("OpenDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarları Açmak İstiyor Musunuz?.
        /// </summary>
        internal static string OpenSettingsMessage {
            get {
                return ResourceManager.GetString("OpenSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Hat Blo. ID.
        /// </summary>
        internal static string Rear_Track_ID {
            get {
                return ResourceManager.GetString("Rear_Track_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Hat Bloğu Boyu(cm).
        /// </summary>
        internal static string Rear_Track_Length {
            get {
                return ResourceManager.GetString("Rear_Track_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Hat Blo. Konumu(cm).
        /// </summary>
        internal static string Rear_Track_Location {
            get {
                return ResourceManager.GetString("Rear_Track_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arka Hat Bloğu Hız Limiti(km/sa).
        /// </summary>
        internal static string Rear_Track_Max_Speed {
            get {
                return ResourceManager.GetString("Rear_Track_Max_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar Bağlanılıyor... - .
        /// </summary>
        internal static string ReConnect {
            get {
                return ResourceManager.GetString("ReConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar Kaydedilemiyor!.
        /// </summary>
        internal static string SerilizationSettingsExceptionMessage {
            get {
                return ResourceManager.GetString("SerilizationSettingsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Atlama Talebi Kabul Edildi.....
        /// </summary>
        internal static string SkipStationAcceptMessage {
            get {
                return ResourceManager.GetString("SkipStationAcceptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Atlama Talebi Reddedildi.....
        /// </summary>
        internal static string SkipStationRejectMessage {
            get {
                return ResourceManager.GetString("SkipStationRejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hız (km/sa).
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam MA Uzunluğu(cm).
        /// </summary>
        internal static string Total_Route_Distance {
            get {
                return ResourceManager.GetString("Total_Route_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren Adı.
        /// </summary>
        internal static string Train_Name {
            get {
                return ResourceManager.GetString("Train_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren Ayarları.
        /// </summary>
        internal static string TrainSettingsModal {
            get {
                return ResourceManager.GetString("TrainSettingsModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlanılıyor... -.
        /// </summary>
        internal static string TryConnect {
            get {
                return ResourceManager.GetString("TryConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlanılıyor... - .
        /// </summary>
        internal static string TryToConnect {
            get {
                return ResourceManager.GetString("TryToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyonda Tutma Aktif Olduğu İçin Tren Bekliyor.....
        /// </summary>
        internal static string WaitingForHoldStation {
            get {
                return ResourceManager.GetString("WaitingForHoldStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tren Hareket Yetkisi Gelmediği İçin Bekliyor....
        /// </summary>
        internal static string WaitingForMA {
            get {
                return ResourceManager.GetString("WaitingForMA", resourceCulture);
            }
        }
    }
}
